print("      *  *  *     ")
print("    *         *   ")
print("  *    Which   *  ")
print(" *  came first: * ")
print("*  the  chicken  *")
print(" *   or   the   * ")
print(" *   egg?   *")
print("     *  *  *     ")